[tool.poetry]
name = "wisper_test"
version = "0.1.0"
description = ""
authors = ["VeterAN <vet-an@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.10"
whisper = "^1.1.10"
ffmpeg = "^1.4"
transformers = "^4.37.2"
torch = "^2.2.0"
accelerate = "^0.26.1"
sentencepiece = "^0.1.99"
sacremoses = "^0.1.1"
openai-whisper = "^20231117"
pydub = "^0.25.1"
python-dotenv = "^1.0.1"
loguru = "^0.7.2"
pillow = "^10.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
skip_gitignore = true
skip_glob = ["**/migrations/*", "**/settings/*"]
src_paths = ["<your_code_dir>"]

[tool.mypy]
mypy_path = "./src"
follow_imports = "silent"
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]